### ISSUE TITLE
Script fails on latest 'known good' emacs build

### ISSUE THREAD

**Issue by neovimnovum** [mclear-tools/build-emacs-macos#2]
First, thank you for writing this script - it's the only way I've been able to get nativecomp to work on my M1 pro.

Problem: The build script fails on the latest 'known good' nightly build of emacs, 48cb9c4aaadfe7bd50c13f658a6e8e9e97587867 . I will edit this issue later with the exact error message, but it's to do with libxml2. I can confirm that the issue is caused by emacs itself, as building the previous known good nightly, 8c8093aa6f20a7a4f3799cbdb9270cac013ef71d , works fine. I know I should expect errors when doing nightly builds, just thought you should know in case some change in emacs is going to break this script in the future.

Steps to reproduce: Call the provided script and pass it 48cb9c4aaadfe7bd50c13f658a6e8e9e97587867.

Things tried: brew reinstalling all dependencies.

Potential cause: Something that was changed between the two versions: https://github.com/emacs-mirror/emacs/compare/8c8093aa6f20a7a4f3799cbdb9270cac013ef71d...48cb9c4aaadfe7bd50c13f658a6e8e9e97587867/ . I'm going to try to narrow this down by attempting builds on intermediate commits later.

**Comment by jrtorsella** [comment]
I have found that the issue was introduced at some point between commits 735b45191041778824460807ee5bf4d1cebd3421 and cca47ae555bfddf87b4871988555738c335f8457 , likely at d82e1a873df381b2c35bc9036da5665468bdfd31 (just based on the commit message involving webp, I haven't tried to build it). Compare link: https://github.com/emacs-mirror/emacs/compare/735b45191041778824460807ee5bf4d1cebd3421...cca47ae555bfddf87b4871988555738c335f8457/ . Here's the first error the script reports; the libxml error is there always and even on successful builds - the -lwebp error is new.

ld: warning: directory not found for option '-L/opt/homebrewopt/libxml2/lib'
ld: library not found for -lwebp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [temacs] Error 1
make[1]: *** [src] Error 2

Edit: Is homebrewopt correct? Or is there a typo in line 40 of the install script?

**Comment by mclearc** [comment]
Thanks for looking into this! I'll try and have a look this weekend and see what's going wrong.

**Comment by jrtorsella** [comment]
Thank you! I think I may have figured out the issue - I added a link to webp and the slash between homebrew and opt, and things build perfectly for me now. Opened a PR to show what ended up working, obviously don't feel obligated to merge. Thank you again for the script!
